CREATE DATABASE [Lueftungssteuerung]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Lueftungssteuerung', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Lueftungssteuerung.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Lueftungssteuerung_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Lueftungssteuerung_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Lueftungssteuerung] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [Lueftungssteuerung] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Lueftungssteuerung] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Lueftungssteuerung] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Lueftungssteuerung] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Lueftungssteuerung] SET ARITHABORT OFF 
GO
ALTER DATABASE [Lueftungssteuerung] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Lueftungssteuerung] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Lueftungssteuerung] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [Lueftungssteuerung] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Lueftungssteuerung] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Lueftungssteuerung] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Lueftungssteuerung] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Lueftungssteuerung] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Lueftungssteuerung] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Lueftungssteuerung] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Lueftungssteuerung] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Lueftungssteuerung] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Lueftungssteuerung] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Lueftungssteuerung] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Lueftungssteuerung] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Lueftungssteuerung] SET  READ_WRITE 
GO
ALTER DATABASE [Lueftungssteuerung] SET RECOVERY FULL 
GO
ALTER DATABASE [Lueftungssteuerung] SET  MULTI_USER 
GO
ALTER DATABASE [Lueftungssteuerung] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Lueftungssteuerung] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Lueftungssteuerung] SET DELAYED_DURABILITY = DISABLED 
GO
USE [Lueftungssteuerung]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [Lueftungssteuerung]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [Lueftungssteuerung] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

USE [Lueftungssteuerung]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Stufen]') AND type in (N'U'))
DROP TABLE [dbo].[Stufen]
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Stufen]
   (
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Stufe] [int] NULL,
	[Bezeichnung] Varchar(255) NULL,
	[Drehzahl] [int] NULL,
	[Leistung] [int] NULL,
   [Spannung] [int] NULL,
   [AktivJN] [bit] NOT NULL
   ) ON [PRIMARY]
GO

INSERT INTO Stufen 
   (Stufe, Bezeichnung, Drehzahl, Leistung, Spannung, AktivJN)
Values
   (0, 'Aus', 0, 0, 0, 1),
   (1, 'Stufe 1', 30, 15, 230, 0),
   (2, 'Stufe 2', 60, 45, 230, 0),
   (3, 'Stufe X', 90, 60, 230, 0)

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Aufzeichnung]') AND type in (N'U'))
DROP TABLE [dbo].[Aufzeichnung]
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Aufzeichnung]
   (
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Drehzahl] [int] NULL,
	[Leistung] [int] NULL,
   [Spannung] [int] NULL,
   [Zeitstempel] [DateTime] NULL
   ) ON [PRIMARY]
GO